server:
  port: 8085
spring:
  application:
    name: scloud-custom-ribbo-server
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
