server:
  port: 8084
#做微服务的时候，该名称很重要，供其他服务访问用
spring:
  application:
    name: scloud-movie-server-ribbon
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}
#做负载均衡的时候，不需要配置这个地址
#user:
#  userServicePath: http://localhost:8082

