server:
  port: 8082
# jpa配置 数据源配置
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: scloud-user-server
#日志配置
logging:
  level: info
  org.hibernate: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.bibernate.type.descriptor.sql.BasicExtractor: TRACE
  com.springms: DEBUG
#eureka配置
eureka:
#  server:
#    enable-self-preservation: false  禁止Eureka Server自我保护机制
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ppm  # eureka 可以理解的元数据
      age: 18 # 不会影响客户端行为
#    appname: appname-springms-provider-user    # 直接显示的是App应用的名称，在 http://localhost:8761/ 地址处可以看到该注册服务的应用名称

#    # 这里我们就先注释掉，知道这个 hostname 的用法就可以了，先注释掉不影响后面的测试
#    hostname: user              # 然后我们就可以通过 http://user:7900/simple/1 来访问我们的地址了

info:
  app.name: SpringCloudProject
  company.name: xxxx
  build.artifactId: $project.artifactId$
  build.version: $project.version$